import { Geist, Geist_Mono , Poppins} from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber/Navber";
import Footer from "./components/Footer/Footer";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const popins = Poppins({
  weight:["400", "600", "700"],
  subsets: ["latin"],
})

export const metadata = {
  title: {
    template : "%s | first NextJs App",
    default : "first NextJs App"
  },
  description: "Generated by create next app",
  keywords: ['Next.js', 'React', 'JavaScript'],
  creator: [{ name: 'Abdul Karim', url: 'https://abdul-karim-portfolio.netlify.app/' }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
         <body
           className={`${popins.className} antialiased`}
         >
           <section className="min-h-screen">
             <Navber/>
             <div className="mt-5">
                {children}
             </div>
             <div className="sticky top-full">
               <Footer/>
             </div>
           </section>
         </body>
      </NextAuthSessionProvider>
    </html>
  );
}
